REQUIRED_GOVERNMENT_WARNING = (
    "GOVERNMENT WARNING: (1) ACCORDING TO THE SURGEON GENERAL,\n"
    "WOMEN SHOULD NOT DRINK ALCOHOLIC BEVERAGES DURING\n"
    "PREGNANCY BECAUSE OF THE RISK OF BIRTH DEFECTS. (2) CONSUMPTION\n"
    "OF ALCOHOLIC BEVERAGES IMPAIRS YOUR ABILITY TO DRIVE A CAR\n"
    "OR OPERATE MACHINERY, AND MAY CAUSE HEALTH PROBLEMS."
)
